language: node_js

node_js:
    - "node"
    - "6"
    - "7"

sudo: false

git:
    submodules: false

install_script:
    - make install

script:
    - make test

after_success:
    - npm run codecoverage
