version: "2"
services:
    express:
        build:
            context: .
            dockerfile: Docker/Dockerfile-express
        environment:
            - DBWEBB_PORT=1337
            - DBWEBB_DSN=mongodb://mongodb:27017/test
        volumes:
            - ./:/app/
        ports:
            - 1337:1337
        links:
            - mongodb
        command: "npm start"
    mongodb:
        image: mongo
        environment:
            - MONGO_DATA_DIR=/data3/db
        volumes:
            - ./data3/db:/data3/db
        ports:
            - 27017:27017
        command: mongod --bind_ip_all
